### ISSUE TITLE
Use local names as notations instead of labels

### ISSUE THREAD

**Issue by nichtich** [marcelotto/skout#1]
Most [of our vocabularies](https://github.com/gbv/jskos-data/) are based on local identifiers which also are used as notations. How about:

~~~yaml
base_iri: http://example.com/
notations: true  # turn local identifiers into notations
---
foo:
- =: Foo   # shorthand for :prefLabel:
- bar
~~~

~~~turtle
@prefix : <http://example.com/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

:foo
    a skos:Concept ;
    skos:notation "foo" ;
    skos:prefLabel "Foo"@en ;
    skow:narrower :bar .

:bar 
    a skos:Concept ;
    skos:notation "bar" ;
    skos:broader :foo .
~~~

**Comment by marcelotto** [comment]
Good idea. I'll try to implement this in the next version. But of course PRs are also very welcome.

**Comment by marcelotto** [comment]
I went a slightly different route which nevertheless supports your requested feature. You can now define the property to be used with the `label_type` field in the preamble. See more in the CHANGELOG and the updated README.

I didn't add the `prefLabel` shorthand, because I'm planning to support user-defined properties and don't want to take this operator, which would be more suitable for the equivalence property of choice of the user.
